from enum import StrEnum


class JobStatus(StrEnum):
    NEW = "NEW"
    TRIAGE = "TRIAGE"
    READY = "READY"
    ASSIGNING = "ASSIGNING"
    SCHEDULED = "SCHEDULED"
    IN_PROGRESS = "IN_PROGRESS"
    DONE = "DONE"
    INVOICED = "INVOICED"
    PAID = "PAID"
    BLOCKED = "BLOCKED"
    CANCELLED = "CANCELLED"


class AssignmentState(StrEnum):
    SENT = "SENT"
    DELIVERED = "DELIVERED"
    RESPONDED = "RESPONDED"
    EXPIRED = "EXPIRED"
    FAILED = "FAILED"


class ResponseAnswer(StrEnum):
    YES = "YES"
    NO = "NO"
    MAYBE = "MAYBE"


class EventScope(StrEnum):
    EMAIL = "EMAIL"
    PUSH = "PUSH"
    WORKFLOW = "WORKFLOW"
    IMPORT = "IMPORT"
    SYSTEM = "SYSTEM"


class EventLevel(StrEnum):
    INFO = "INFO"
    WARN = "WARN"
    ERROR = "ERROR"


class ReasonCode(StrEnum):
    MISSING_EMAIL = "MISSING_EMAIL"
    MISSING_PHONE = "MISSING_PHONE"
    MISSING_LOCATION = "MISSING_LOCATION"
    MISSING_TENANT = "MISSING_TENANT"
    INVALID_CONTACT = "INVALID_CONTACT"
    TIMEWINDOW_BLOCK = "TIMEWINDOW_BLOCK"
    GRACE_BLOCK = "GRACE_BLOCK"
    DAILY_LIMIT_BLOCK = "DAILY_LIMIT_BLOCK"
    BATCH_LIMIT_BLOCK = "BATCH_LIMIT_BLOCK"
    STATUS_BLOCK = "STATUS_BLOCK"
    UNSUBSCRIBED = "UNSUBSCRIBED"
    OPTIN_REQUIRED = "OPTIN_REQUIRED"
    DO_NOT_CONTACT = "DO_NOT_CONTACT"
    BOUNCE = "BOUNCE"
    PROVIDER_ERROR = "PROVIDER_ERROR"
    NETWORK_ERROR = "NETWORK_ERROR"
    AUTH_ERROR = "AUTH_ERROR"
    UNKNOWN_ERROR = "UNKNOWN_ERROR"
